-- 扩充技术栈标签覆盖面（用于现有环境，无需重置数据库）
INSERT INTO tags (slug, label, group_name, color_hex, is_preset) VALUES
  -- 前端框架与工程化
  ('nuxt', 'Nuxt', '前端框架', '#00DC82', TRUE),
  ('svelte', 'Svelte', '前端框架', '#FF3E00', TRUE),
  ('solidjs', 'SolidJS', '前端框架', '#2C4F7C', TRUE),
  ('angular', 'Angular', '前端框架', '#DD0031', TRUE),
  ('webpack', 'Webpack', '前端工程化', '#8DD6F9', TRUE),
  ('vite', 'Vite', '前端工程化', '#646CFF', TRUE),
  ('rollup', 'Rollup', '前端工程化', '#EC4A3F', TRUE),
  ('pnpm', 'pnpm', '前端工程化', '#F69220', TRUE),
  ('storybook', 'Storybook', '前端工程化', '#FF4785', TRUE),
  ('reactnative', 'React Native', '客户端开发', '#61DAFB', TRUE),
  ('flutter', 'Flutter', '客户端开发', '#02569B', TRUE),
  ('swift', 'Swift', '客户端开发', '#FA7343', TRUE),
  ('kotlin', 'Kotlin', '客户端开发', '#7F52FF', TRUE),

  -- 后端框架与服务治理
  ('nestjs', 'NestJS', '后端框架', '#E0234E', TRUE),
  ('express', 'Express', '后端框架', '#000000', TRUE),
  ('koa', 'Koa', '后端框架', '#333333', TRUE),
  ('springcloud', 'Spring Cloud', '后端框架', '#6DB33F', TRUE),
  ('dubbo', 'Dubbo', '后端框架', '#2F54EB', TRUE),
  ('grpc', 'gRPC', '服务治理', '#244C5A', TRUE),
  ('graphql', 'GraphQL', '服务治理', '#E10098', TRUE),
  ('apollo', 'Apollo GraphQL', '服务治理', '#311C87', TRUE),
  ('mybatis', 'MyBatis', '后端框架', '#B07219', TRUE),
  ('kratos', 'Kratos', '后端框架', '#00ADD8', TRUE),
  ('echo', 'Echo', '后端框架', '#00ADD8', TRUE),
  ('celery', 'Celery', '后端框架', '#37814A', TRUE),

  -- 数据库与中间件
  ('oracle', 'Oracle', '数据库', '#F80000', TRUE),
  ('sqlite', 'SQLite', '数据库', '#003B57', TRUE),
  ('mariadb', 'MariaDB', '数据库', '#003545', TRUE),
  ('tidb', 'TiDB', '数据库', '#E32322', TRUE),
  ('clickhouse', 'ClickHouse', '数据库', '#FFCC01', TRUE),
  ('doris', 'Apache Doris', '数据库', '#4444AA', TRUE),
  ('hbase', 'HBase', '数据库', '#CC0000', TRUE),
  ('dynamodb', 'DynamoDB', '数据库', '#4053D6', TRUE),
  ('rabbitmq', 'RabbitMQ', '中间件', '#FF6600', TRUE),
  ('rocketmq', 'RocketMQ', '中间件', '#D81E06', TRUE),
  ('activemq', 'ActiveMQ', '中间件', '#ED8B00', TRUE),
  ('nacos', 'Nacos', '中间件', '#3F8CFF', TRUE),
  ('zookeeper', 'ZooKeeper', '中间件', '#A97BFF', TRUE),

  -- AI 应用与模型工程
  ('rag', 'RAG', 'AI方向', '#4B0082', TRUE),
  ('agent', 'Agent', 'AI方向', '#4B0082', TRUE),
  ('langchain', 'LangChain', 'AI方向', '#4B0082', TRUE),
  ('llamaindex', 'LlamaIndex', 'AI方向', '#4B0082', TRUE),
  ('vllm', 'vLLM', 'AI方向', '#4B0082', TRUE),
  ('ollama', 'Ollama', 'AI方向', '#4B0082', TRUE),
  ('tgi', 'Text Generation Inference', 'AI方向', '#4B0082', TRUE),
  ('trl', 'TRL', 'AI方向', '#4B0082', TRUE),
  ('peft', 'PEFT', 'AI方向', '#4B0082', TRUE),
  ('loratuning', 'LoRA 微调', 'AI方向', '#4B0082', TRUE),
  ('sft', 'SFT', 'AI方向', '#4B0082', TRUE),
  ('dpo', 'DPO', 'AI方向', '#4B0082', TRUE),
  ('rlhf', 'RLHF', 'AI方向', '#4B0082', TRUE),
  ('prompteng', 'Prompt Engineering', 'AI方向', '#4B0082', TRUE),
  ('evals', 'LLM Evals', 'AI方向', '#4B0082', TRUE),
  ('vectordb', '向量数据库', 'AI方向', '#4B0082', TRUE),
  ('faiss', 'FAISS', 'AI方向', '#4B0082', TRUE),
  ('milvus', 'Milvus', 'AI方向', '#4B0082', TRUE),
  ('qdrant', 'Qdrant', 'AI方向', '#4B0082', TRUE),
  ('weaviate', 'Weaviate', 'AI方向', '#4B0082', TRUE),
  ('transformers', 'Hugging Face Transformers', 'AI方向', '#4B0082', TRUE),
  ('diffusers', 'Diffusers', 'AI方向', '#4B0082', TRUE),
  ('deepspeed', 'DeepSpeed', 'AI方向', '#4B0082', TRUE),
  ('megatron', 'Megatron-LM', 'AI方向', '#4B0082', TRUE),
  ('tensorrtllm', 'TensorRT-LLM', 'AI方向', '#4B0082', TRUE),

  -- 数据工程与计算
  ('airflow', 'Airflow', '大数据', '#017CEE', TRUE),
  ('dbt', 'dbt', '大数据', '#FF694B', TRUE),
  ('hive', 'Hive', '大数据', '#FDEE21', TRUE),
  ('presto', 'Presto/Trino', '大数据', '#2E77BC', TRUE),
  ('trino', 'Trino', '大数据', '#DD00A1', TRUE),
  ('beam', 'Apache Beam', '大数据', '#FF6D00', TRUE),

  -- 云原生与运维
  ('helm', 'Helm', '云服务', '#0F1689', TRUE),
  ('istio', 'Istio', '云服务', '#466BB0', TRUE),
  ('prometheus', 'Prometheus', 'DevOps', '#E6522C', TRUE),
  ('grafana', 'Grafana', 'DevOps', '#F46800', TRUE),
  ('opentelemetry', 'OpenTelemetry', 'DevOps', '#425CC7', TRUE),
  ('ansible', 'Ansible', 'DevOps', '#EE0000', TRUE),
  ('terraform', 'Terraform', 'DevOps', '#7B42BC', TRUE),
  ('jenkins', 'Jenkins', 'DevOps', '#D24939', TRUE),
  ('argo', 'ArgoCD', 'DevOps', '#EF7B4D', TRUE),
  ('nginx', 'Nginx', '基础设施', '#009639', TRUE),
  ('envoy', 'Envoy', '基础设施', '#AC6199', TRUE),

  -- 安全
  ('owasp', 'OWASP', '安全方向', '#222222', TRUE),
  ('burpsuite', 'Burp Suite', '安全方向', '#FF6633', TRUE),
  ('metasploit', 'Metasploit', '安全方向', '#1F4E79', TRUE),
  ('siem', 'SIEM', '安全方向', '#D71A1B', TRUE),

  -- 测试与质量
  ('junit', 'JUnit', '测试工程', '#25A162', TRUE),
  ('pytest', 'Pytest', '测试工程', '#0A9EDC', TRUE),
  ('playwright', 'Playwright', '测试工程', '#2EAD33', TRUE),
  ('cypress', 'Cypress', '测试工程', '#17202C', TRUE),
  ('selenium', 'Selenium', '测试工程', '#43B02A', TRUE),
  ('postman', 'Postman', '测试工程', '#FF6C37', TRUE)
ON CONFLICT (slug) DO NOTHING;

