-- 第三级细分技术标签
INSERT INTO tags (slug, label, group_name, color_hex, is_preset) VALUES
  ('cpp-stl', 'STL', 'C++细分', '#F34B7D', TRUE),
  ('cpp-inline', 'inline', 'C++细分', '#F34B7D', TRUE),
  ('cpp-template', '模板编程', 'C++细分', '#F34B7D', TRUE),
  ('cpp-memory', '内存模型', 'C++细分', '#F34B7D', TRUE),
  ('java-jvm', 'JVM', 'Java细分', '#B07219', TRUE),
  ('java-concurrency', '并发编程', 'Java细分', '#B07219', TRUE),
  ('java-collection', '集合框架', 'Java细分', '#B07219', TRUE),
  ('java-io', 'IO/NIO', 'Java细分', '#B07219', TRUE),
  ('python-async', 'AsyncIO', 'Python细分', '#3572A5', TRUE),
  ('python-gil', 'GIL', 'Python细分', '#3572A5', TRUE),
  ('python-metaclass', '元类', 'Python细分', '#3572A5', TRUE),
  ('python-typing', '类型系统', 'Python细分', '#3572A5', TRUE),
  ('go-goroutine', 'Goroutine', 'Go细分', '#00ADD8', TRUE),
  ('go-channel', 'Channel', 'Go细分', '#00ADD8', TRUE),
  ('go-gmp', 'GMP 调度', 'Go细分', '#00ADD8', TRUE),
  ('go-context', 'Context', 'Go细分', '#00ADD8', TRUE),
  ('react-hooks', 'Hooks', 'React细分', '#61DAFB', TRUE),
  ('react-state', '状态管理', 'React细分', '#61DAFB', TRUE),
  ('react-ssr', 'SSR/CSR', 'React细分', '#61DAFB', TRUE),
  ('react-performance', '性能优化', 'React细分', '#61DAFB', TRUE),
  ('vue-composition', 'Composition API', 'Vue细分', '#41B883', TRUE),
  ('vue-router', 'Vue Router', 'Vue细分', '#41B883', TRUE),
  ('vue-pinia', 'Pinia', 'Vue细分', '#41B883', TRUE),
  ('vue-performance', '渲染优化', 'Vue细分', '#41B883', TRUE),
  ('springboot-mvc', 'Spring MVC', 'Spring Boot细分', '#6DB33F', TRUE),
  ('springboot-aop', 'AOP', 'Spring Boot细分', '#6DB33F', TRUE),
  ('springboot-jpa', 'JPA', 'Spring Boot细分', '#6DB33F', TRUE),
  ('springboot-security', 'Spring Security', 'Spring Boot细分', '#6DB33F', TRUE),
  ('django-orm', 'ORM', 'Django细分', '#092E20', TRUE),
  ('django-middleware', 'Middleware', 'Django细分', '#092E20', TRUE),
  ('django-auth', 'Auth', 'Django细分', '#092E20', TRUE),
  ('django-rest', 'Django REST', 'Django细分', '#092E20', TRUE),
  ('fastapi-dependency', '依赖注入', 'FastAPI细分', '#009688', TRUE),
  ('fastapi-async', '异步路由', 'FastAPI细分', '#009688', TRUE),
  ('fastapi-pydantic', 'Pydantic', 'FastAPI细分', '#009688', TRUE),
  ('fastapi-openapi', 'OpenAPI', 'FastAPI细分', '#009688', TRUE),
  ('node-eventloop', 'Event Loop', 'Node.js细分', '#339933', TRUE),
  ('node-stream', 'Stream', 'Node.js细分', '#339933', TRUE),
  ('node-cluster', 'Cluster', 'Node.js细分', '#339933', TRUE),
  ('node-buffer', 'Buffer', 'Node.js细分', '#339933', TRUE),
  ('mysql-index', '索引优化', 'MySQL细分', '#4479A1', TRUE),
  ('mysql-transaction', '事务隔离', 'MySQL细分', '#4479A1', TRUE),
  ('mysql-lock', '锁机制', 'MySQL细分', '#4479A1', TRUE),
  ('mysql-sharding', '分库分表', 'MySQL细分', '#4479A1', TRUE),
  ('redis-cache', '缓存策略', 'Redis细分', '#DC382D', TRUE),
  ('redis-lock', '分布式锁', 'Redis细分', '#DC382D', TRUE),
  ('redis-pipeline', 'Pipeline', 'Redis细分', '#DC382D', TRUE),
  ('redis-ha', '高可用', 'Redis细分', '#DC382D', TRUE),
  ('kafka-topic', 'Topic/Partition', 'Kafka细分', '#231F20', TRUE),
  ('kafka-group', '消费组', 'Kafka细分', '#231F20', TRUE),
  ('kafka-idempotent', '幂等生产', 'Kafka细分', '#231F20', TRUE),
  ('kafka-eos', 'Exactly Once', 'Kafka细分', '#231F20', TRUE),
  ('docker-image', '镜像构建', 'Docker细分', '#2496ED', TRUE),
  ('docker-network', '网络模式', 'Docker细分', '#2496ED', TRUE),
  ('docker-volume', 'Volume', 'Docker细分', '#2496ED', TRUE),
  ('docker-multistage', '多阶段构建', 'Docker细分', '#2496ED', TRUE),
  ('k8s-deployment', 'Deployment', 'K8s细分', '#326CE5', TRUE),
  ('k8s-service', 'Service', 'K8s细分', '#326CE5', TRUE),
  ('k8s-ingress', 'Ingress', 'K8s细分', '#326CE5', TRUE),
  ('k8s-hpa', 'HPA', 'K8s细分', '#326CE5', TRUE),
  ('pytorch-autograd', 'Autograd', 'PyTorch细分', '#EE4C2C', TRUE),
  ('pytorch-distributed', '分布式训练', 'PyTorch细分', '#EE4C2C', TRUE),
  ('pytorch-dataloader', 'DataLoader', 'PyTorch细分', '#EE4C2C', TRUE),
  ('pytorch-amp', 'AMP', 'PyTorch细分', '#EE4C2C', TRUE),
  ('tensorflow-graph', '计算图', 'TensorFlow细分', '#FF6F00', TRUE),
  ('tensorflow-keras', 'Keras', 'TensorFlow细分', '#FF6F00', TRUE),
  ('tensorflow-serving', 'TF Serving', 'TensorFlow细分', '#FF6F00', TRUE),
  ('tensorflow-distributed', '分布式训练', 'TensorFlow细分', '#FF6F00', TRUE),
  ('llm-prompt', 'Prompt Engineering', 'LLM细分', '#4B0082', TRUE),
  ('llm-functioncalling', 'Function Calling', 'LLM细分', '#4B0082', TRUE),
  ('llm-evals', 'Evals', 'LLM细分', '#4B0082', TRUE),
  ('llm-agent', 'Agent 框架', 'LLM细分', '#4B0082', TRUE),
  ('rag-rewrite', 'Query Rewrite', 'RAG细分', '#4B0082', TRUE),
  ('rag-hybrid', 'Hybrid Search', 'RAG细分', '#4B0082', TRUE),
  ('rag-rerank', 'Rerank', 'RAG细分', '#4B0082', TRUE),
  ('rag-compression', 'Context Compression', 'RAG细分', '#4B0082', TRUE),
  ('vllm-pagedattention', 'PagedAttention', 'vLLM细分', '#4B0082', TRUE),
  ('vllm-batching', 'Continuous Batching', 'vLLM细分', '#4B0082', TRUE),
  ('vllm-kvcache', 'KV Cache', 'vLLM细分', '#4B0082', TRUE),
  ('vllm-tp', 'Tensor Parallel', 'vLLM细分', '#4B0082', TRUE)
ON CONFLICT (slug) DO NOTHING;

