-- ============================================================
-- 500+ 公司招聘官网种子数据
-- 覆盖互联网、AI、游戏、硬件、金融、新能源等所有主流科技公司
-- ============================================================

-- 创建公司招聘官网表
CREATE TABLE IF NOT EXISTS company_careers (
  id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  careers_url TEXT NOT NULL,
  detail_url TEXT,
  source VARCHAR(50) NOT NULL DEFAULT 'manual',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  last_crawled_at TIMESTAMPTZ,
  last_crawl_status VARCHAR(20),
  job_count INT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(company_id, careers_url)
);

-- companies.name 上加唯一约束（幂等，已存在则跳过）
DO $$
BEGIN
  ALTER TABLE companies ADD CONSTRAINT companies_name_key UNIQUE (name);
EXCEPTION WHEN duplicate_object THEN
  RAISE NOTICE 'companies_name_key constraint already exists, skipping';
END $$;

CREATE INDEX IF NOT EXISTS idx_company_careers_status ON company_careers(status);
CREATE INDEX IF NOT EXISTS idx_company_careers_source ON company_careers(source);

-- 确保官网直接投递爬虫已启用（只更新，不删除）
UPDATE job_sources SET is_enabled = TRUE WHERE source_name = '官网直接投递';
INSERT INTO job_sources (source_name, source_type, priority, is_enabled)
VALUES ('官网直接投递', 'public', 10, TRUE)
ON CONFLICT DO NOTHING;

DO $$
DECLARE
  company_data TEXT[] := ARRAY[
    -- ═══ 互联网大厂 ═══ (Top tier)
    -- 字节跳动
    '字节跳动|字节|互联网|https://jobs.bytedance.com/|https://jobs.bytedance.com/campus|字节招聘|byteDance|btyd',
    '字节游戏|字节游戏|游戏|https://game.bytedance.com/campus|https://game.bytedance.com/campus|朝夕光年',
    -- 腾讯
    '腾讯|腾讯|互联网|https://careers.tencent.com/|https://careers.tencent.com/campus.html|腾讯招聘',
    -- 阿里巴巴
    '阿里巴巴|阿里|互联网|https://campus.alibaba.com/|https://campus.alibaba.com/|阿里校招|alibaba|ali',
    '淘天集团|淘天|电商|https://campus.taotian.com/|https://campus.taotian.com/|淘天招聘',
    '阿里云|阿里云|云计算|https://campus.aliyun.com/|https://campus.aliyun.com/|阿里云招聘',
    '蚂蚁集团|蚂蚁|金融科技|https://campus.antgroup.com/|https://campus.antgroup.com/|蚂蚁招聘|antgroup',
    '菜鸟集团|菜鸟|物流|https://campus.cainiao.com/|https://campus.cainiao.com/|菜鸟招聘',
    '飞猪旅行|飞猪|旅游|https://campus.fliggy.com/|https://campus.fliggy.com/|飞猪招聘',
    '阿里健康|阿里健康|医疗|https://campus.alihealth.cn/|https://campus.alihealth.cn/',
    -- 美团
    '美团|美团|互联网|https://campus.meituan.com/|https://campus.meituan.com/|美团校招|meituan|mt',
    -- 京东
    '京东|京东|电商|https://careers.jd.com/|https://careers.jd.com/|京东招聘|jd|jd.com',
    '京东科技|京东科技|AI|https://campus.jdcloud.com/|https://campus.jdcloud.com/|京东云招聘',
    -- 百度
    '百度|百度|互联网|https://talent.baidu.com/|https://talent.baidu.com/|百度招聘|baidu|bd',
    '百度Apollo|百度apollo|自动驾驶|https://apollo.baidu.com/campus|https://apollo.baidu.com/campus|Apollo招聘',
    -- 网易
    '网易|网易|互联网|https://campus.163.com/|https://campus.163.com/|网易招聘|netEase|netease|163',
    '雷火游戏|雷火|游戏|https://campus.leihuo.163.com/|https://campus.leihuo.163.com/|雷火招聘',
    '互娱|网易互娱|游戏|https://campus.xy.163.com/|https://campus.xy.163.com/|网易游戏招聘',
    -- 快手
    '快手|快手|短视频|https://campus.kuaishou.cn/|https://campus.kuaishou.cn/|快手招聘|kuaishou|ks',
    -- 小红书
    '小红书|小红书|社交电商|https://job.xiaohongshu.com/|https://job.xiaohongshu.com/|小红书招聘|xhs|redbook',
    -- 哔哩哔哩
    '哔哩哔哩|哔哩|B站|https://campus.bilibili.com/|https://campus.bilibili.com/|B站招聘|bilibili|blbl|bilibili',
    -- 拼多多
    '拼多多|拼多多|pinduoduo|https://www.pinduoduo.com/careers|https://www.pinduoduo.com/careers|多多招聘|pdd',
    -- 滴滴出行
    '滴滴出行|滴滴|DIDI|https://campus.didiglobal.com/|https://campus.didiglobal.com/|滴滴招聘|didi|DiDi',
    '滴滴自动驾驶|滴滴|自动驾驶|https://idol.aiyoux.com/|https://idol.aiyoux.com/|滴滴自动驾驶',
    -- 蚂蚁分工
    '饿了么|阿里本地生活|本地生活|https://campus.ele.me/|https://campus.ele.me/|饿了么招聘',
    '口碑|阿里口碑|本地生活|https://campus.koubei.com/|https://campus.koubei.com/',
    -- 58同城
    '58同城|58|分类信息|https://campus.58.com/|https://campus.58.com/|58招聘|58|58.com',
    '赶集网|赶集|分类信息|https://campus.ganji.com/|https://campus.ganji.com/|',
    -- 字节系其他
    '巨量引擎|巨量引擎|广告|https://campus.oceanengine.com/|https://campus.oceanengine.com/|巨量招聘',
    '飞书|飞书|办公软件|https://campus.feishu.cn/|https://campus.feishu.cn/|飞书招聘|feishu|lark',
    '朝夕光年|朝夕光年|游戏|https://game.bytedance.com/campus|https://game.bytedance.com/campus/',
    '番茄小说|字节|内容|https://campus.bytedance.com/positionDetail?id=33004|https://campus.bytedance.com/positionDetail?id=33004|',
    '汽水音乐|字节|音乐|https://campus.bytedance.com/positionDetail?id=33501|https://campus.bytedance.com/positionDetail?id=33501|',
    -- 腾讯系其他
    '腾讯云|腾讯云|云计算|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|腾讯云招聘',
    '微信支付|腾讯|支付|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|微信支付招聘',
    '腾讯游戏|腾讯游戏|游戏|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|腾讯游戏招聘',
    '腾讯地图|腾讯|地图|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|腾讯地图招聘',
    '腾讯视频|腾讯|视频|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|腾讯视频招聘',
    '腾讯音乐|腾讯音乐|音乐|https://campus.tencentmusic.com/|https://campus.tencentmusic.com/|腾讯音乐招聘|tme',
    '阅文集团|阅文|网文|https://campus.yuewen.com/|https://campus.yuewen.com/|阅文招聘|yuewen|qidian',
    '搜狗|搜狗|搜索|https://campus.sogou.com/|https://campus.sogou.com/|搜狗招聘|sogou',
    'QQ浏览器|腾讯|浏览器|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|',
    -- 字节教育
    '大力教育|字节|教育|https://campus.bytedance.com/college?keywords=教育|https://campus.bytedance.com/college?keywords=教育|大力教育招聘',
    '清北网校|大力教育|教育|https://campus.bytedance.com/positionDetail?id=33005|https://campus.bytedance.com/positionDetail?id=33005|',
    '瓜瓜龙|大力教育|教育|https://campus.bytedance.com/positionDetail?id=33006|https://campus.bytedance.com/positionDetail?id=33006|',
    -- 其他互联网
    '爱奇艺|爱奇艺|视频|https://campus.iqiyi.com/|https://campus.iqiyi.com/|爱奇艺招聘|iqiyi',
    '优酷|优酷|视频|https://campus.youku.com/|https://campus.youku.com/|优酷招聘|youku|youku',
    '芒果TV|芒果TV|视频|https://campus.mgtv.com/|https://campus.mgtv.com/|芒果TV招聘|mgtv',
    '搜狐|搜狐|互联网|https://campus.sohu.com/|https://campus.sohu.com/|搜狐招聘|sohu',
    '新浪|新浪|互联网|https://campus.sina.com.cn/|https://campus.sina.com.cn/|新浪招聘|sina',
    '微博|微博|社交|https://campus.weibo.com/|https://campus.weibo.com/|微博招聘|weibo',
    '汽车之家|汽车之家|汽车媒体|https://campus.autohome.com.cn/|https://campus.autohome.com.cn/|汽车之家招聘|autohome',
    '贝壳|贝壳|房产|https://campus.ke.com/|https://campus.ke.com/|贝壳招聘|ke.com|beike',
    '自如|自如|长租公寓|https://campus.ziroom.com/|https://campus.ziroom.com/|自如招聘|ziroom',
    'Keep|Keep|运动健身|https://campus.keep.com/|https://campus.keep.com/|Keep招聘',
    'Soul|Soul|社交|https://campus.soulapp.cn/|https://campus.soulapp.cn/|Soul招聘',
    '作业帮|作业帮|教育|https://campus.zuoyebang.com/|https://campus.zuoyebang.com/|作业帮招聘',
    '猿辅导|猿辅导|教育|https://campus.yuanfudao.com/|https://campus.yuanfudao.com/|猿辅导招聘',
    '掌门教育|掌门|教育|https://campus.zhangmen.com/|https://campus.zhangmen.com/|掌门招聘',
    '一起学|一起学|教育|https://campus.17zuoye.com/|https://campus.17zuoye.com/|一起学招聘',
    '高途|高途|教育|https://campus.gaotu.com/|https://campus.gaotu.com/|高途招聘|gaotu',
    '好未来|好未来|教育|https://career.tal.com/|https://career.tal.com/|好未来招聘|tal|xes|xueersi',
    '新东方|新东方|教育|https://campus.offcn.com/|https://campus.offcn.com/|新东方招聘|offcn',
    '学而思|学而思|教育|https://campus.xes.cn/|https://campus.xes.cn/|学而思招聘|xueersi',
    'VIPKID|VIPKID|教育|https://campus.vipkid.com.cn/|https://campus.vipkid.com.cn/|VIPKID招聘',
    '有道|有道|教育|https://campus.youdao.com/|https://campus.youdao.com/|有道招聘|youdao',
    '喜马拉雅|喜马拉雅|音频|https://campus.ximalaya.com/|https://campus.ximalaya.com/|喜马拉雅招聘|ximalaya',
    '蜻蜓FM|蜻蜓|音频|https://campus.qingting.fm/|https://campus.qingting.fm/|蜻蜓FM招聘',
    '今日头条|字节|内容|https://jobs.bytedance.com/campus|https://jobs.bytedance.com/campus|头条招聘',
    '西瓜视频|字节|视频|https://campus.bytedance.com/positionDetail?id=33007|https://campus.bytedance.com/positionDetail?id=33007|',
    -- ═══ AI 大模型公司 ═══ (Top priority)
    '月之暗面|Moonshot|AI|https://www.moonshot.cn/|https://www.moonshot.cn/|Moonshot招聘|kimi|Kimi',
    '智谱AI|智谱|AI|https://www.zhipuai.cn/careers|https://www.zhipuai.cn/careers|智谱招聘|zhipuai|glm',
    '零一万物|零一|AI|https://www.01.ai/careers|https://www.01.ai/careers|零一招聘|01ai',
    '百川智能|百川|AI|https://www.baichuan-ai.com/careers|https://www.baichuan-ai.com/careers|百川招聘|baichuan',
    'Minimax|海螺AI|AI|https://careers.minimax.io/|https://careers.minimax.io/|MiniMax招聘|minimax',
    '面壁智能|面壁|AI|https://www.modelbest.cn/careers|https://www.modelbest.cn/careers|面壁招聘',
    '深势科技|深势|AI|https://www.dptech.com/careers|https://www.dptech.com/careers|深势招聘|dptech',
    '硅基流动|硅基|AI|https://siliconflow.ai/careers|https://siliconflow.ai/careers|硅基招聘',
    '必优科技|必优|AI|https://www.bingou.cn/careers|https://www.bingou.cn/careers|',
    '出门问问|出门问问|AI|https://www.chumenwenwen.com/careers|https://www.chumenwenwen.com/careers|出门问问招聘',
    '第四范式|第四范式|AI|https://www.4paradigm.com/careers|https://www.4paradigm.com/careers|第四范式招聘',
    '九章云极|九章|AI|https://www.zetyun.com/careers|https://www.zetyun.com/careers|九章招聘',
    '同盾科技|同盾|AI|https://www.tongdun.cn/careers|https://www.tongdun.cn/careers|同盾招聘',
    '云从科技|云从|AI|https://www.cloudwalk.com/careers|https://www.cloudwalk.com/careers|云从招聘|cloudwalk',
    '云知声|云知声|AI|https://www.unisound.com/careers|https://www.unisound.com/careers|云知声招聘',
    '声网|声网|AI|https://www.agora.io/careers|https://www.agora.io/careers|声网招聘|agora',
    '蓦然认知|蓦然|AI|https://www.morebot.com/careers|https://www.morebot.com/careers|蓦然招聘',
    '猎豹移动|猎豹|AI|https://campus.cmcm.com/|https://campus.cmcm.com/|猎豹招聘|cmcm',
    '三角兽|三角兽|AI|https://www.sanbot.com/careers|https://www.sanbot.com/careers|三角兽招聘',
    '薄言RS|薄言|AI|https://www.ruan.ai/careers|https://www.ruan.ai/careers|薄言招聘',
    '车来了|车来了|AI|https://www.chelaile.com.cn/careers|https://www.chelaile.com.cn/careers|车来了招聘',
    '汇量科技|汇量|AI|https://www.mobvista.com/careers|https://www.mobvista.com/careers|汇量招聘|mobvista',
    '热云数据|热云|AI|https://www.hotcloud.cn/careers|https://www.hotcloud.cn/careers|热云招聘',
    '数美科技|数美|AI|https://www.ishumei.com/careers|https://www.ishumei.com/careers|数美招聘',
    'DataVisor|DataVisor|AI|https://www.datavisor.com/careers|https://www.datavisor.com/careers|DataVisor招聘',
    '华控清交|华控|AI|https://www.hcssdata.com/careers|https://www.hcssdata.com/careers|华控招聘',
    '瑞莱智慧|瑞莱|AI|https://www.realai.cn/careers|https://www.realai.cn/careers|瑞莱招聘',
    '墨奇科技|墨奇|AI|https://www.moqikey.com/careers|https://www.moqikey.com/careers|墨奇招聘',
    -- ═══ AI Infra / 算力 ═══
    '燧原科技|燧原|AI芯片|https://www.enflame.cn/careers|https://www.enflame.cn/careers|燧原招聘|enflame',
    '天数智芯|天数|AI芯片|https://www.iluvatar.cn/careers|https://www.iluvatar.cn/careers|天数招聘|iluvatar',
    '沐曦|沐曦|AI芯片|https://www.metax-tech.com/careers|https://www.metax-tech.com/careers|沐曦招聘|metax',
    '海光信息|海光|AI芯片|https://www.hygon.cn/careers|https://www.hygon.cn/careers|海光招聘|hygon',
    '壁仞科技|壁仞|AI芯片|https://www.biren.tech/careers|https://www.biren.tech/careers|壁仞招聘|biren',
    '摩尔线程|摩尔线程|AI芯片|https://www.mthreads.com/careers|https://www.mthreads.com/careers|摩尔招聘|mthreads',
    '芯动科技|芯动|AI芯片|https://www.innoSilicon.com/careers|https://www.innoSilicon.com/careers|芯动招聘|innosilicon',
    '龙芯中科|龙芯|CPU|https://www.loongson.cn/careers|https://www.loongson.cn/careers|龙芯招聘|loongson',
    '申威科技|申威|CPU|https://www.shenwei.com/careers|https://www.shenwei.com/careers|申威招聘',
    '兆芯|兆芯|CPU|https://www.zhaoxin.com/careers|https://www.zhaoxin.com/careers|兆芯招聘|zhaoxin',
    '飞腾|飞腾|CPU|https://www.phytium.com.cn/careers|https://www.phytium.com.cn/careers|飞腾招聘|phytium',
    '华为海思|华为海思|芯片|https://career.huawei.com/|https://career.huawei.com/|海思招聘|hisilicon',
    '紫光展锐|展锐|芯片|https://www.unisoc.com/careers|https://www.unisoc.com/careers|展锐招聘|unisoc',
    -- ═══ 计算机视觉 / 安防 ═══
    '商汤科技|商汤|CV|https://www.sensetime.com/careers|https://www.sensetime.com/careers|商汤招聘|sensetime',
    '旷视科技|旷视|CV|https://career.megvii.com/|https://career.megvii.com/|旷视招聘|megvii',
    '依图科技|依图|CV|https://www.yitutech.com/careers|https://www.yitutech.com/careers|依图招聘|yitu',
    '海康威视|海康|CV|https://campus.hikvision.com/|https://campus.hikvision.com/|海康招聘|hikvision',
    '大华股份|大华|CV|https://www.dahuatech.com/careers|https://www.dahuatech.com/careers|大华招聘|dahua',
    '宇视科技|宇视|CV|https://www.uniview.com/careers|https://www.uniview.com/careers|宇视招聘|uniview',
    '智慧眼科技|智慧眼|CV|https://www.aitrace.com/careers|https://www.aitrace.com/careers|智慧眼招聘',
    '格林深瞳|格林|CV|https://www.deepglint.com/careers|https://www.deepglint.com/careers|格林招聘|deepglint',
    '格灵深瞳|格灵|CV|https://www.deepglint.com/careers|https://www.deepglint.com/careers|格灵招聘',
    '虹软科技|虹软|CV|https://www.arcsoft.com.cn/careers|https://www.arcsoft.com.cn/careers|虹软招聘|arcsoft',
    '创新奇智|创新奇智|CV|https://www.chuangxin-ai.com/careers|https://www.chuangxin-ai.com/careers|创新招聘',
    '算能科技|算能|CV|https://www.sophon.ai/careers|https://www.sophon.ai/careers|算能招聘|sophon',
    '海致科技|海致|数据|https://www.haizhi.com/careers|https://www.haizhi.com/careers|海致招聘',
    -- ═══ 自动驾驶 ═══
    '小马智行|小马|pony.ai|https://career.pony.ai/|https://career.pony.ai/|小马招聘|pony.ai|pony',
    'Momenta|魔门塔|自动驾驶|https://www.momenta.cn/careers|https://www.momenta.cn/careers|Momenta招聘',
    '文远知行|文远|自动驾驶|https://www.weride.ai/careers|https://www.weride.ai/careers|文远招聘|weride',
    '元戎启行|元戎|自动驾驶|https://www.deeproute.ai/careers|https://www.deeproute.ai/careers|元戎招聘|deeproute',
    'AutoX|安途|自动驾驶|https://www.autox.com/careers|https://www.autox.com/careers|AutoX招聘|autox',
    '轻舟智航|轻舟|自动驾驶|https://www.qcraft.ai/careers|https://www.qcraft.ai/careers|轻舟招聘|qcraft',
    '图森未来|图森|自动驾驶|https://www.tusimple.com/careers|https://www.tusimple.com/careers|图森招聘|tusimple',
    '挚途科技|挚途|自动驾驶|https://www.zhitu-tech.com/careers|https://www.zhitu-tech.com/careers|挚途招聘',
    '希迪智驾|希迪|自动驾驶|https://www.cidi.cn/careers|https://www.cidi.cn/careers|希迪招聘|cidi',
    '中智行|中智行|自动驾驶|https://www.zonycom.com/careers|https://www.zonycom.com/careers|中智行招聘',
    '禾多科技|禾多|自动驾驶|https://www.holo.ai/careers|https://www.holo.ai/careers|禾多招聘|holo',
    '主线科技|主线|自动驾驶|https://www.mainline.ai/careers|https://www.mainline.ai/careers|主线招聘',
    -- ═══ 机器人 ═══
    '大疆创新|大疆|无人机|https://campus.dji.com/|https://campus.dji.com/|大疆招聘|dji',
    '普渡科技|普渡|机器人|https://www.pudutech.com/careers|https://www.pudutech.com/careers|普渡招聘|pudu',
    '擎朗智能|擎朗|机器人|https://www.keenon.com/careers|https://www.keenon.com/careers|擎朗招聘|keenon',
    '猎豹移动机器人|猎豹|机器人|https://www.cmcm.com/careers|https://www.cmcm.com/careers|猎豹机器人招聘',
    '科沃斯|科沃斯|机器人|https://www.ecovacs.com/careers|https://www.ecovacs.com/careers|科沃斯招聘|ecovacs',
    '石头科技|石头|扫地机器人|https://www.roborock.com/campus|https://www.roborock.com/campus|石头招聘|roborock',
    '云鲸智能|云鲸|机器人|https://www.yunji-robot.com/careers|https://www.yunji-robot.com/careers|云鲸招聘',
    '追觅科技|追觅|机器人|https://www.dreametech.com/campus|https://www.dreametech.com/campus|追觅招聘|dreametech',
    '九号公司|九号|Ninebot|https://www.ninebot.com/campus|https://www.ninebot.com/campus|九号招聘|ninebot|segway',
    '极飞科技|极飞|无人机|https://www.xag.com/careers|https://www.xag.com/careers|极飞招聘|xag',
    '亿嘉和|亿嘉和|机器人|https://www.yijiahe.com/careers|https://www.yijiahe.com/careers|亿嘉和招聘',
    -- ═══ 游戏公司 ═══ (High priority)
    '米哈游|miHoYo|游戏|https://career.mihoyo.com/|https://career.mihoyo.com/|米哈游招聘|mihoyo|miHoYo|原神',
    '莉莉丝游戏|莉莉丝|游戏|https://lilithgames.jobs.feishu.cn/campus|https://lilithgames.jobs.feishu.cn/campus|莉莉丝招聘|lilith',
    '鹰角网络|鹰角|游戏|https://career.hypergryph.com/|https://career.hypergryph.com/|鹰角招聘|hypergryph|明日方舟',
    '库洛游戏|库洛|游戏|https://careers.kurogame.com/|https://careers.kurogame.com/|库洛招聘|kurogame|鸣潮',
    '叠纸游戏|叠纸|游戏|https://campus.papergames.com/|https://campus.papergames.com/|叠纸招聘|papergames|暖暖',
    '完美世界|完美|游戏|https://campus.wanmei.com/|https://campus.wanmei.com/|完美招聘|perfect|wanmei',
    '盛趣游戏|盛趣|游戏|https://campus.shengqu.com/|https://campus.shengqu.com/|盛趣招聘|shengqu|shanda',
    '西山居|西山居|游戏|https://campus.seasun.cn/|https://campus.seasun.cn/|西山居招聘|seasun|剑网3',
    '网易游戏|网易游戏|游戏|https://campus.163.com/|https://campus.163.com/|网易游戏招聘|netease game',
    '光子工作室|腾讯|游戏|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|光子招聘',
    '天美工作室|腾讯|游戏|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|天美招聘|TIM',
    '魔方工作室|腾讯|游戏|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|魔方招聘',
    '北极光工作室|腾讯|游戏|https://careers.tencent.com/campus.html|https://careers.tencent.com/campus.html|北极光招聘',
    '波克城市|波克|游戏|https://campus.boke.com/|https://campus.boke.com/|波克招聘|boke',
    '游族网络|游族|游戏|https://campus.youzu.com/|https://campus.youzu.com/|游族招聘|youzu',
    'IGG|IGG|游戏|https://www.igg.com/campus|https://www.igg.com/campus|IGG招聘',
    '多益网络|多益|游戏|https://www.duoyi.com/campus|https://www.duoyi.com/campus|多益招聘|duoyi',
    '吉比特|吉比特|游戏|https://www.g-bits.com/campus|https://www.g-bits.com/campus|吉比特招聘|gbits|雷霆',
    '4399|4399|游戏|https://campus.4399.com/|https://campus.4399.com/|4399招聘',
    '英雄互娱|英雄|游戏|https://campus.yingxiong.com/|https://campus.yingxiong.com/|英雄互娱招聘',
    '巨人网络|巨人|游戏|https://campus.ztgame.com.cn/|https://campus.ztgame.com.cn/|巨人招聘|ztgame',
    '完美世界游戏|完美|游戏|https://campus.wanmei.com/|https://campus.wanmei.com/|完美游戏招聘',
    '龙腾简合|龙腾|游戏|https://www.lt-corp.com/campus|https://www.lt-corp.com/campus|龙腾招聘',
    'FunPlus|趣加|游戏|https://www.funplus.com/campus|https://www.funplus.com/campus|FunPlus招聘|funplus',
    '网易雷火|雷火|游戏|https://campus.leihuo.163.com/|https://campus.leihuo.163.com/|雷火招聘',
    '网易互娱|互娱|游戏|https://campus.xy.163.com/|https://campus.xy.163.com/|互娱招聘',
    '灵犀互娱|灵犀|游戏|https://campus.lingxigames.com/|https://campus.lingxigames.com/|灵犀招聘',
    'Hotcool|热酷|游戏|https://www.hotcool.com/campus|https://www.hotcool.com/campus|Hotcool招聘',
    '网龙|网龙|游戏|https://campus.netdragon.com/|https://campus.nd.com.cn/campus|网龙招聘|nd|netease-inc',
    '乐元素|乐元素|游戏|https://campus.leiyuansu.com/|https://campus.leiyuansu.com/|乐元素招聘',
    '天梯|天梯|游戏|https://www.ttcgame.com/campus|https://www.ttcgame.com/campus|天梯招聘',
    -- ═══ 云计算 / 云原生 ═══ (High priority)
    '华为云|华为云|IaaS|https://career.huawei.com/|https://career.huawei.com/|华为云招聘|huaweicloud',
    '字节云|火山引擎|云|https://campus.volcengine.com/|https://campus.volcengine.com/|火山引擎招聘|volcengine',
    '百度智能云|百度云|IaaS|https://talent.baidu.com/|https://talent.baidu.com/|百度云招聘|baidu cloud|bce',
    '京东云|京东云|IaaS|https://campus.jdcloud.com/|https://campus.jdcloud.com/|京东云招聘|jdcloud',
    '天翼云|天翼|云|https://campus.chinatelecom.cn/|https://campus.chinatelecom.cn/|天翼云招聘|ctyun',
    '移动云|移动|云|https://campus.cmcc.chinamobile.com/|https://campus.cmcc.chinamobile.com/|移动云招聘',
    '联通云|联通|云|https://campus.chinaunicom.cn/|https://campus.chinaunicom.cn/|联通云招聘',
    '青云科技|青云|IaaS|https://www.qingcloud.com/campus|https://www.qingcloud.com/campus|青云招聘|qingcloud',
    'UCloud|优刻得|IaaS|https://www.ucloud.cn/campus|https://www.ucloud.cn/campus|UCloud招聘|ucloud',
    '金山云|金山云|IaaS|https://campus.ksyun.com/|https://campus.ksyun.com/|金山云招聘|ksyun|kingsoft',
    '七牛云|七牛|云存储|https://www.qiniu.com/campus|https://www.qiniu.com/campus|七牛招聘|qiniu',
    '又拍云|又拍|CDN|https://www.upyun.com/campus|https://www.upyun.com/campus|又拍云招聘|upyun',
    '白山云|白山|CDN|https://www.baishan.com/campus|https://www.baishan.com/campus|白山招聘|baishan',
    '网宿科技|网宿|CDN|https://www.wangsu.com/campus|https://www.wangsu.com/campus|网宿招聘|wangsu',
    '帝恩思|帝恩思|DNS|https://www.dns.com/campus|https://www.dns.com/campus|DNS.COM招聘',
    '云智慧|云智慧|APM|https://www.cloudwise.com/campus|https://www.cloudwise.com/campus|云智慧招聘',
    '博云|博云|PaaS|https://www.bocloud.com.cn/campus|https://www.bocloud.com.cn/campus|博云招聘|bocloud',
    '灵雀云|灵雀云|PaaS|https://www.alauda.cn/campus|https://www.alauda.cn/campus|灵雀招聘|alauda',
    '时速云|时速云|PaaS|https://www.speedycloud.cn/campus|https://www.speedycloud.cn/campus|时速云招聘',
    '数人云|数人云|PaaS|https://www.shurenyun.com/campus|https://www.shurenyun.com/campus|数人云招聘',
    '才云|才云|PaaS|https://www.caicloud.io/campus|https://www.caicloud.io/careers|才云招聘|caicloud',
    '谐云科技|谐云|容器|https://www.harmonycloud.cn/campus|https://www.harmonycloud.cn/campus|谐云招聘',
    '云杉网络|云杉|SDN|https://www.yunshan.com/campus|https://www.yunshan.com/campus|云杉招聘',
    '数列科技|数列|数据库|https://www.shulie.io/campus|https://www.shulie.io/campus|数列招聘',
    -- ═══ 大数据 / 数据中台 ═══
    '星环科技|星环|大数据|https://www.transwarp.cn/campus|https://www.transwarp.cn/campus|星环招聘|transwarp',
    'Kyligence|Kyligence|大数据|https://www.kyligence.io/campus|https://www.kyligence.io/campus|Kyligence招聘',
    'DataCanvas|九章云极|大数据|https://www.datacanvas.com/campus|https://www.datacanvas.com/campus|DataCanvas招聘',
    '柏睿数据|柏睿|大数据|https://www.rapidscroll.com/campus|https://www.rapidscroll.com/campus|柏睿招聘',
    '超对称|超对称|数据|https://www.symtech.com/campus|https://www.symtech.com/campus|超对称招聘',
    '富数科技|富数|隐私计算|https://www.fudata.cn/campus|https://www.fudata.cn/campus|富数招聘',
    '氪信科技|氪信|金融AI|https://www.creditx.com/campus|https://www.creditx.com/campus|氪信招聘|creditx',
    '冰鉴科技|冰鉴|金融AI|https://www.jimi.ai/campus|https://www.jimi.ai/campus|冰鉴招聘|jimi',
    '拍拍贷|拍拍贷|金融科技|https://www.ppdai.com/campus|https://www.ppdai.com/campus|拍拍贷招聘|ppdai',
    '维信金科|维信|金融科技|https://www.vcredit.com/campus|https://www.vcredit.com/campus|维信招聘',
    '品钛|品钛|金融科技|https://www.pintec.com/campus|https://www.pintec.com/campus|品钛招聘|pintec',
    '量化派|量化派|金融科技|https://www.lpsqb.com/campus|https://www.lpsqb.com/campus|量化派招聘',
    -- ═══ 网络安全 ═══
    '奇安信|奇安信|安全|https://campus.qianxin.com/|https://campus.qianxin.com/|奇安信招聘|qianxin',
    '深信服|深信服|安全|https://hr.sangfor.com/|https://hr.sangfor.com/|深信服招聘|sangfor',
    '启明星辰|启明|安全|https://www.venustech.com.cn/campus|https://www.venustech.com.cn/campus|启明招聘|venustech',
    '绿盟科技|绿盟|安全|https://www.nsfocus.com.cn/campus|https://www.nsfocus.com.cn/campus|绿盟招聘|nsfocus',
    '安恒信息|安恒|安全|https://www.dbappsecurity.com.cn/campus|https://www.dbappsecurity.com.cn/campus|安恒招聘|dbappsecurity',
    '天融信|天融信|安全|https://www.topsec.com.cn/campus|https://www.topsec.com.cn/campus|天融信招聘|topsec',
    '新华三|新华三|安全|https://www.h3c.com/campus|https://www.h3c.com/campus|新华三招聘|h3c',
    '华为安全|华为|安全|https://career.huawei.com/|https://career.huawei.com/|华为安全招聘',
    '知道创宇|知道创宇|安全|https://www.knownsec.com/campus|https://www.knownsec.com/campus|知道招聘|knownsec',
    '长亭科技|长亭|安全|https://www.ctfiki.com/campus|https://www.ctfiki.com/campus|长亭招聘|chaitin',
    '安天实验室|安天|安全|https://www.antiy.com/campus|https://www.antiy.com/campus|安天招聘|antiy',
    '东软|东软|安全|https://www.neusoft.com/campus|https://www.neusoft.com/campus|东软招聘|neusoft',
    '中孚信息|中孚|安全|https://www.zhongfu.net/campus|https://www.zhongfu.net/campus|中孚招聘',
    '北信源|北信源|安全|https://www.vrv.com.cn/campus|https://www.vrv.com.cn/campus|北信源招聘|vrv',
    '山石网科|山石|安全|https://www.hillstonenet.com.cn/campus|https://www.hillstonenet.com.cn/campus|山石招聘|hillstone',
    '亚信安全|亚信|安全|https://www.asiainfo.com/campus|https://www.asiainfo.com/campus|亚信招聘|asiainfo',
    '恒安嘉新|恒安|安全|https://www.eversec.com.cn/campus|https://www.eversec.com.cn/campus|恒安招聘',
    '任子行|任子行|安全|https://www.renzixing.com/campus|https://www.renzixing.com/campus|任子行招聘',
    '蓝月亮|蓝月亮|安全|https://www.bluemoon.com.cn/campus|https://www.bluemoon.com.cn/campus|蓝月亮招聘',
    -- ═══ 芯片 / 半导体 ═══ (High priority)
    '寒武纪|寒武纪|AI芯片|https://www.cambricon.com/careers|https://www.cambricon.com/careers|寒武纪招聘|cambricon',
    '地平线机器人|地平线|AI芯片|https://campus.horizon.ai/|https://campus.horizon.ai/|地平线招聘|horizon',
    '平头哥|平头哥|芯片|https://career.huawei.com/|https://career.huawei.com/|平头哥招聘|t-head',
    '比特大陆|比特大陆|AI芯片|https://www.bitmain.com/campus|https://www.bitmain.com/campus|比特大陆招聘|bitmain|antminer',
    '嘉楠科技|嘉楠|AI芯片|https://www.canaan.io/campus|https://www.canaan.io/campus|嘉楠招聘|canaan|k210',
    '遂原科技|遂原|AI芯片|https://www.suiruan.com/campus|https://www.suiruan.com/campus|遂原招聘',
    '爱芯元智|爱芯|AI芯片|https://www.axera-tech.com/campus|https://www.axera-tech.com/campus|爱芯招聘|axera',
    '芯驰科技|芯驰|车规芯片|https://www.semidrive.com/campus|https://www.semidrive.com/campus|芯驰招聘|semidrive',
    '黑芝麻智能|黑芝麻|AI芯片|https://www.blacksesame.com.cn/campus|https://www.blacksesame.com.cn/campus|黑芝麻招聘',
    '晶心科技|晶心|CPU|https://www.andestech.com/campus|https://www.andestech.com/campus|晶心招聘|andestech',
    '芯来科技|芯来|RISC-V|https://www.nucleisys.com/campus|https://www.nucleisys.com/campus|芯来招聘|nuclei',
    '中科海讯|中科海讯|芯片|https://www.haisun.com/campus|https://www.haisun.com/campus|中科海讯招聘',
    -- 保留 tfme/封装 + 长电/封装 + 华天/封装
    -- ═══ 智能硬件 / 手机 ═══
    '华为|华为|硬件|https://career.huawei.com/|https://career.huawei.com/|华为招聘|huawei',
    '小米|小米|手机|https://campus.xiaomi.com/|https://campus.xiaomi.com/|小米招聘|xiaomi|mi',
    'OPPO|OPPO|手机|https://careers.oppo.com/university/oppo/campus|https://careers.oppo.com/university/oppo/campus|OPPO招聘',
    'VIVO|VIVO|手机|https://hr-campus.vivo.com/campus/jobs|https://hr-campus.vivo.com/campus/jobs|VIVO招聘|vivo',
    '荣耀|荣耀|手机|https://www.hihonor.com/campus|https://www.hihonor.com/campus|荣耀招聘|honor',
    'realme|真我|手机|https://campus.realme.com/|https://campus.realme.com/|realme招聘',
    '一加|一加|手机|https://campus.oneplus.com/|https://campus.oneplus.com/|一加招聘|oneplus',
    '传音控股|传音|手机|https://campus.transsion.com/|https://campus.transsion.com/|传音招聘|transsion|tecno',
    '联想|联想|PC|https://campus.lenovo.com.cn/|https://campus.lenovo.com.cn/|联想招聘|lenovo',
    '华硕|华硕|PC|https://campus.asus.com.cn/|https://campus.asus.com.cn/|华硕招聘|asus',
    '戴尔|戴尔|PC|https://www.dell.com/cn/careers|https://www.dell.com/cn/careers|戴尔招聘|dell',
    '惠普|惠普|PC|https://campus.hp.com/|https://campus.hp.com/|惠普招聘|hp',
    '英特尔|Intel|芯片|https://jobs.intel.com/cn|https://jobs.intel.com/cn|英特尔招聘|intel',
    'AMD|AMD|芯片|https://www.amd.com/en/careers|https://www.amd.com/en/careers|AMD招聘',
    '英伟达|NVIDIA|芯片|https://www.nvidia.com/en-us/careers|https://www.nvidia.com/en-us/careers|NVIDIA招聘',
    '高通|高通|芯片|https://www.qualcomm.com/careers|https://www.qualcomm.com/careers|高通招聘|qualcomm',
    '联发科|联发科|芯片|https://www.mediatek.com/careers|https://www.mediatek.com/careers|联发科招聘|mediatek|mtk',
    '安森美|安森美|芯片|https://www.onsemi.com/careers|https://www.onsemi.com/careers|安森美招聘|onsemi',
    '恩智浦|NXP|芯片|https://www.nxp.com/careers|https://www.nxp.com/careers|NXP招聘',
    '意法半导体|ST|芯片|https://www.st.com/careers|https://www.st.com/careers|ST招聘|STM32|stmicro',
    '德州仪器|TI|芯片|https://www.ti.com/careers|https://www.ti.com/careers|TI招聘|ti|texas',
    'Microchip|Microchip|芯片|https://www.microchip.com/careers|https://www.microchip.com/careers|Microchip招聘',
    -- ═══ 新能源 / 智能汽车 ═══ (High priority)
    '比亚迪|比亚迪|新能源|https://job.byd.com/|https://job.byd.com/|比亚迪招聘|byd',
    '宁德时代|宁德|新能源|https://talent.catl.com/|https://talent.catl.com/|CATL招聘|catl',
    '蔚来汽车|蔚来|汽车|https://nio.careers/|https://nio.careers/|蔚来招聘|nio',
    '小鹏汽车|小鹏|汽车|https://campus.xpeng.com.cn/|https://campus.xpeng.com.cn/|小鹏招聘|xpeng|xpeng',
    '理想汽车|理想|汽车|https://campus.lixiang.com/|https://campus.lixiang.com/|理想招聘|li auto|li',
    '极氪|极氪|汽车|https://campus.zEEKR.com/|https://campus.zEEKR.com/|极氪招聘|zeekr',
    '零跑汽车|零跑|汽车|https://campus.lixiang.com/|https://campus.lixiang.com/|零跑招聘|leapmotor',
    '哪吒汽车|哪吒|汽车|https://www.nezha.com/campus|https://www.nezha.com/campus|哪吒招聘|nezha',
    '威马汽车|威马|汽车|https://www.wm-motor.com/campus|https://www.wm-motor.com/campus|威马招聘|wm-motor',
    '集度汽车|集度|汽车|https://www.jidu.com/campus|https://www.jidu.com/campus|集度招聘|jidu',
    '小米汽车|小米|汽车|https://campus.xiaomi.com/|https://campus.xiaomi.com/|小米汽车招聘',
    '华为车BU|华为|汽车|https://career.huawei.com/|https://career.huawei.com/|华为汽车招聘',
    '广汽埃安|埃安|汽车|https://campus.gac.com/|https://campus.gac.com/|埃安招聘|aion',
    '长安汽车|长安|汽车|https://campus.changan.com.cn/|https://campus.changan.com.cn/|长安招聘|changan',
    '长城汽车|长城|汽车|https://campus.gwm.com.cn/|https://campus.gwm.com.cn/|长城招聘|gwm|greatewall',
    '吉利汽车|吉利|汽车|https://campus.geely.com/|https://campus.geely.com/|吉利招聘|geely',
    '上汽集团|上汽|汽车|https://campus.saicmotor.com/|https://campus.saicmotor.com/|上汽招聘|saic',
    '上汽零束|零束|汽车|https://www.zlink.cn/campus|https://www.zlink.cn/campus|零束招聘|zlink',
    '智己汽车|智己|汽车|https://www.immotor.com/campus|https://www.immotor.com/campus|智己招聘|immotor',
    '华人运通|华人运通|汽车|https://www.human Horizons.com/campus|https://www.humanHorizons.com/campus|华人运通招聘',
    '华为数字能源|华为|能源|https://career.huawei.com/|https://career.huawei.com/|华为数字能源招聘',
    '阳光电源|阳光|新能源|https://www.sungrowpower.com/campus|https://www.sungrowpower.com/campus|阳光招聘|sungrow',
    '远景能源|远景|新能源|https://www.envision.cn/campus|https://www.envision.cn/campus|远景招聘|envision',
    '隆基绿能|隆基|光伏|https://www.longi.com/cn/careers|https://www.longi.com/cn/careers|隆基招聘|longi|隆基',
    '晶澳科技|晶澳|光伏|https://www.ja-solar.com/campus|https://www.ja-solar.com/campus|晶澳招聘',
    '通威股份|通威|光伏|https://www.tongwei.com/campus|https://www.tongwei.com/campus|通威招聘',
    '天合光能|天合|光伏|https://www.trinasolar.com/campus|https://www.trinasolar.com/campus|天合招聘|trina',
    '晶盛机电|晶盛|光伏|https://www.jingsheng.com/campus|https://www.jingsheng.com/campus|晶盛招聘',
    -- ═══ 企业服务 / SaaS ═══
    '用友网络|用友|SaaS|https://campus.yonyou.com/|https://campus.yonyou.com/|用友招聘|yonyou',
    '金蝶软件|金蝶|SaaS|https://www.kingdee.com/campus|https://www.kingdee.com/campus|金蝶招聘|kingdee',
    '东软集团|东软|IT服务|https://www.neusoft.com/campus|https://www.neusoft.com/campus|东软招聘',
    '中软国际|中软|IT服务|https://www.chinasofti.com/campus|https://www.chinasofti.com/campus|中软招聘|chinasofti',
    '软通动力|软通|IT服务|https://www.isoftstone.com/campus|https://www.isoftstone.com/campus|软通招聘|isoftstone',
    '文思海辉|文思海辉|IT服务|https://www.pactera.com/campus|https://www.pactera.com/campus|文思海辉招聘|pactera',
    '博彦科技|博彦|IT服务|https://www.beyondsoft.com/campus|https://www.beyondsoft.com/campus|博彦招聘|beyondsoft',
    '神州信息|神州信息|IT服务|https://www.dctc.com.cn/campus|https://www.dctc.com.cn/campus|神州信息招聘',
    '华宇软件|华宇|IT服务|https://www.thunisoft.com/campus|https://www.thunisoft.com/campus|华宇招聘|thunisoft',
    '致远互联|致远|协同|https://www.seeyon.com/campus|https://www.seeyon.com/campus|致远招聘|seeyon',
    '泛微|泛微|协同|https://www.fanwe.com/campus|https://www.fanwe.com/campus|泛微招聘|fanwei',
    '蓝凌软件|蓝凌|OA|https://www.landray.com.cn/campus|https://www.landray.com.cn/campus|蓝凌招聘|landray',
    '今目标|今目标|协同|https://www.jingoal.com/campus|https://www.jingoal.com/campus|今目标招聘|jingoal',
    '云之家|云之家|协同|https://www.yunzhijia.com/campus|https://www.yunzhijia.com/campus|云之家招聘',
    '明源云|明源|地产SaaS|https://www.mycicc.com/campus|https://www.mycicc.com/campus|明源招聘|mycic',
    '有赞|有赞|SaaS|https://www.youzan.com/campus|https://www.youzan.com/campus|有赞招聘|youzan',
    '微盟|微盟|SaaS|https://www.weimob.com/campus|https://www.weimob.com/campus|微盟招聘|weimob',
    '光云科技|光云|SaaS|https://www.guangcloud.com.cn/campus|https://www.guangcloud.com.cn/campus|光云招聘',
    '二维火|二维火|SaaS|https://www.2dfire.com/campus|https://www.2dfire.com/campus|二维火招聘',
    '客如云|客如云|SaaS|https://www.keruyun.com/campus|https://www.keruyun.com/campus|客如云招聘|keruyun',
    '美味不用等|美味|餐饮SaaS|https://www.mwee.com/campus|https://www.mwee.com/campus|美味招聘|mwee',
    '校宝在线|校宝|教育SaaS|https://www.xiaoyu.cn/campus|https://www.xiaoyu.cn/campus|校宝招聘|xiaoyu',
    '易快报|易快报|报销SaaS|https://www.17kuaibao.com/campus|https://www.17kuaibao.com/campus|易快报招聘',
    '易企银|易企银|金融SaaS|https://www.eqiyin.com/campus|https://www.eqiyin.com/campus|易企银招聘',
    '北森|北森|HRSaaS|https://www.beisen.com/campus|https://www.beisen.com/campus|北森招聘|beisen',
    'Moka|Moka|HRSaaS|https://www.mokahr.com/campus|https://www.mokahr.com/campus|Moka招聘|moka',
    'i人事|i人事|HRSaaS|https://www.ihr.com/campus|https://www.ihr.com/campus|i人事招聘|ihr',
    '薪人薪事|薪人薪事|HRSaaS|https://www.xinrenxinshi.com/campus|https://www.xinrenxinshi.com/campus|薪人招聘',
    '盖雅工场|盖雅|劳动力|https://www.gaiaworks.cn/campus|https://www.gaiaworks.cn/campus|盖雅招聘|gaiaworks',
    '汇联易|汇联易|报销|https://www.huilianyi.com/campus|https://www.huilianyi.com/campus|汇联易招聘',
    'ONES|ONES|研发管理|https://www.ones.ai/campus|https://www.ones.ai/campus|ONES招聘|ones',
    'Tower|TeamBition|项目管理|https://www.teambition.com/campus|https://www.teambition.com/campus|Tower招聘|teambition',
    'Worktile|Worktile|项目管理|https://www.worktile.com/campus|https://www.worktile.com/campus|Worktile招聘',
    'Teambition|Teambition|项目管理|https://www.teambition.com/campus|https://www.teambition.com/campus|TB招聘',
    '蓝湖|蓝湖|设计|https://www.lanhuapp.com/campus|https://www.lanhuapp.com/campus|蓝湖招聘|lanhu',
    'Miro|Miro|白板|https://miro.com/careers|https://miro.com/careers|Miro招聘',
    'Notion|Notion|协作|https://www.notion.so/careers|https://www.notion.so/careers|Notion招聘',
    'Figma|Figma|设计|https://www.figma.com/careers|https://www.figma.com/careers|Figma招聘',
    'Canva|Canva|设计|https://www.canva.com/careers|https://www.canva.com/careers|Canva招聘',
    -- ═══ 数据库 / 中间件 ═══
    'PingCAP|平凯|数据库|https://www.pingcap.com/campus|https://www.pingcap.com/campus|PingCAP招聘',
    '阿里云数据库|阿里云|数据库|https://campus.aliyun.com/|https://campus.aliyun.com/|阿里云数据库招聘',
    '华为云数据库|华为|数据库|https://career.huawei.com/|https://career.huawei.com/|华为云数据库招聘',
    '巨杉数据库|巨杉|数据库|https://www.sequoiadb.com/campus|https://www.sequoiadb.com/campus|巨杉招聘|sequoiadb',
    '达梦数据库|达梦|DM|https://www.dameng.com/campus|https://www.dameng.com/campus|达梦招聘|dameng',
    '人大金仓|金仓|数据库|https://www.kingbase.com.cn/campus|https://www.kingbase.com.cn/campus|金仓招聘|kingbase',
    '南大通用|南大|数据库|https://www.gbase.cn/campus|https://www.gbase.cn/campus|南大招聘|gbase',
    '优炫软件|优炫|数据库|https://www.uxsino.com/campus|https://www.uxsino.com/campus|优炫招聘|uxsino',
    '神州数码|神州数码|数据库|https://www.digitalchina.com/campus|https://www.digitalchina.com/campus|神州招聘',
    '东方国信|东方国信|大数据|https://www.bonadel.com/campus|https://www.bonadel.com/campus|东方国信招聘|bonadel',
    'SelectDB|SelectDB|OLAP|https://www.selectdb.com/campus|https://www.selectdb.com/campus|SelectDB招聘',
    'DorisDB|DorisDB|OLAP|https://www.dorisdb.com/campus|https://www.dorisdb.com/campus|DorisDB招聘',
    '蚂蚁集团OceanBase|OceanBase|数据库|https://campus.antgroup.com/|https://campus.antgroup.com/|OceanBase招聘|ob|oceanbase',
    'OBCloud|OBCloud|数据库|https://www.oceanbase.com/cloud|https://www.oceanbase.com/cloud|OBC招聘',
    'PingDB|平凯|时序|https://www.pingcap.com/campus|https://www.pingcap.com/campus|PingDB招聘',
    'TDengine|TDengine|时序|https://www.taosdata.com/campus|https://www.taosdata.com/campus|TDengine招聘',
    'MatrixOne|MatrixOne|数据库|https://www.matrixorigin.cn/campus|https://www.matrixorigin.cn/campus|MatrixOne招聘',
    'YMatrix|YMatrix|数据库|https://www.ymatrix.cn/campus|https://www.ymatrix.cn/campus|YMatrix招聘',
    -- ═══ 中间件 / 基础软件 ═══
    'Apache APISIX|apisix|中间件|https://apisix.apache.org/careers|https://apisix.apache.org/careers|APISIX招聘',
    'ShardingSphere|ShardingSphere|中间件|https://www.shardingsphere.apache.org/careers|https://www.shardingsphere.apache.org/careers|SS招聘',
    'ByteTCC|ByteTCC|分布式事务|https://www.dromara.org/campus|https://www.dromara.org/campus|BTCC招聘',
    'Hutool|Hutool|工具库|https://www.hutool.cn/campus|https://www.hutool.cn/campus|Hutool招聘',
    'Apache ShenYu|ShenYu|网关|https://shenyu.apache.org/careers|https://shenyu.apache.org/careers|ShenYu招聘',
    'Apache Dubbo|Dubbo|中间件|https://dubbo.apache.org/careers|https://dubbo.apache.org/careers|Dubbo招聘',
    'Apache RocketMQ|RocketMQ|中间件|https://rocketmq.apache.org/careers|https://rocketmq.apache.org/careers|RMQ招聘',
    'Apache Kafka|Kafka|中间件|https://kafka.apache.org/careers|https://kafka.apache.org/careers|Kafka招聘',
    'Apache Flink|Flink|计算|https://flink.apache.org/careers|https://flink.apache.org/careers|Flink招聘',
    'Apache Spark|Spark|计算|https://spark.apache.org/careers|https://spark.apache.org/careers|Spark招聘',
    'Apache Flink CDC|FlinkCDC|数据|https://www.ververica.com/campus|https://www.ververica.com/campus|Ververica招聘|ververica',
    'DataX|DataX|数据交换|https://github.com/alibaba/DataX|https://github.com/alibaba/DataX|DataX',
    'Canal|Canal|数据同步|https://github.com/alibaba/canal|https://github.com/alibaba/canal|Canal',
    'Sentinel|Sentinel|限流|https://sentinelguard.io/campus|https://sentinelguard.io/campus|Sentinel招聘|sentinel',
    'Nacos|Nacos|配置|https://nacos.io/campus|https://nacos.io/campus|Nacos招聘',
    'Dapr|Dapr|中间件|https://dapr.io/careers|https://dapr.io/careers|Dapr招聘',
    -- ═══ 医疗科技 ═══
    '平安好医生|平安健康|医疗|https://www.pingan.cn/jobs|https://www.pingan.cn/jobs|平安好医生招聘',
    '平安医保科技|平安|医疗|https://www.pingan.cn/jobs|https://www.pingan.cn/jobs|平安医保招聘',
    '东软医疗|东软|医疗|https://www.neusofthis.com/campus|https://www.neusofthis.com/campus|东软医疗招聘',
    '万达信息|万达信息|医疗|https://www.wondershare.cn/campus|https://www.wondershare.cn/campus|万达信息招聘',
    '创业慧康|创业慧康|医疗|https://www.bsoft.com.cn/campus|https://www.bsoft.com.cn/campus|创业慧康招聘',
    '卫宁健康|卫宁|医疗|https://www.wing-health.com/campus|https://www.wing-health.com/campus|卫宁招聘|winhm',
    '思创医惠|思创|医疗|https://www.strategy.com.cn/campus|https://www.strategy.com.cn/campus|思创招聘',
    '和仁科技|和仁|医疗|https://www.hr-med.com/campus|https://www.hr-med.com/campus|和仁招聘',
    '麦迪科技|麦迪|医疗|https://www.medic-tech.com/campus|https://www.medic-tech.com/campus|麦迪招聘',
    '九安医疗|九安|医疗|https://www.ian.com.cn/campus|https://www.ian.com.cn/campus|九安招聘|ian',
    '鱼跃医疗|鱼跃|医疗|https://www.yuyue.com.cn/campus|https://www.yuyue.com.cn/campus|鱼跃招聘|yuyue',
    '联影医疗|联影|医疗设备|https://www.united-imaging.com/campus|https://www.united-imaging.com/campus|联影招聘|united-imaging',
    '迈瑞医疗|迈瑞|医疗设备|https://www.mindray.com/campus|https://www.mindray.com/campus|迈瑞招聘|mindray',
    '开立医疗|开立|医疗设备|https://www.starrad.com/campus|https://www.starrad.com/campus|开立招聘|star',
    '华大基因|华大|基因|https://www.bgi.com/campus|https://www.bgi.com/campus|华大招聘|bgi',
    '诺禾致源|诺禾|基因|https://www.novogene.com/campus|https://www.novogene.com/campus|诺禾招聘|novogene',
    '泛生子|泛生子|基因|https://www.pangente.com/campus|https://www.pangente.com/campus|泛生子招聘',
    '零氪科技|零氪|医疗AI|https://www.linkdoc.com.cn/campus|https://www.linkdoc.com.cn/campus|零氪招聘|linkdoc',
    '医渡云|医渡云|医疗AI|https://www.yiducloud.com.cn/campus|https://www.yiducloud.com.cn/campus|医渡招聘|yiducloud',
    '左手医生|左手|医疗AI|https://www.zuoyishouyi.com/campus|https://www.zuoyishouyi.com/campus|左手招聘',
    '推想科技|推想|医疗AI|https://www.enjoy超频.cn/campus|https://www.enjoy超频.cn/campus|推想招聘',
    '深睿医疗|深睿|医疗AI|https://www.deepwise.com/campus|https://www.deepwise.com/campus|深睿招聘',
    '数坤科技|数坤|医疗AI|https://www.4dmed.com/campus|https://www.4dmed.com/campus|数坤招聘',
    '科大讯飞医疗|讯飞医疗|医疗AI|https://www.iflytek.com/medical/campus|https://www.iflytek.com/medical/campus|讯飞医疗招聘',
    -- ═══ 金融科技 ═══
    '京东金融|京东|金融|https://careers.jd.com/|https://careers.jd.com/|京东金融招聘',
    '度小满|度小满|金融|https://www.duxiaoman.com/campus|https://www.duxiaoman.com/campus|度小满招聘|dxm',
    '陆金所|陆金所|金融|https://www.lu.com/campus|https://www.lu.com/campus|陆金所招聘|lu|lufax',
    '挖财|挖财|金融|https://www.wacai.com/campus|https://www.wacai.com/campus|挖财招聘|wacai',
    '随手记|随手记|金融|https://www.feidee.com/campus|https://www.feidee.com/campus|随手记招聘',
    '51信用卡|51信用卡|金融|https://www.u51.com/campus|https://www.u51.com/campus|51信用卡招聘',
    '我来贷|我来贷|金融|https://www.wolaidai.com/campus|https://www.wolaidai.com/campus|我来贷招聘',
    '小赢科技|小赢|金融|https://www.xiaoying.com/campus|https://www.xiaoying.com/campus|小赢招聘',
    '萨摩耶金服|萨摩耶|金融|https://www.symto.com/campus|https://www.symto.com/campus|萨摩耶招聘',
    '同程金服|同程|金融|https://www.ly.com/campus|https://www.ly.com/campus|同程金服招聘',
    '宁银理财|宁银|理财|https://www.nbcbank.com.cn/campus|https://www.nbcbank.com.cn/campus|宁银招聘|nbc',
    '招银网络|招银|金融|https://www.cmibdl.com/campus|https://www.cmibdl.com/campus|招银招聘|cmibdl',
    '招银云创|招银|金融|https://www.cmyc.com.cn/campus|https://www.cmyc.com.cn/campus|招银云创招聘',
    '招银科技|招银|金融|https://www.cmit.com.cn/campus|https://www.cmit.com.cn/campus|招银科技招聘',
    '建信金科|建信|金融|https://www.ccbft.com/campus|https://www.ccbft.com/campus|建信招聘|ccbft',
    '工银科技|工银|金融|https://www.icbc-tec.com/campus|https://www.icbc-tec.com/campus|工银科技招聘',
    '中银金科|中银|金融|https://www.bocft.com/campus|https://www.bocft.com/campus|中银招聘|bocft',
    '农银金科|农银|金融|https://www.abchina.com/campus|https://www.abchina.com/campus|农银招聘',
    '交银金科|交银|金融|https://www.bankcomm.com/campus|https://www.bankcomm.com/campus|交银招聘',
    '兴业银行|兴业银行|金融|https://www.cib.com.cn/campus|https://www.cib.com.cn/campus|兴业招聘|cib',
    '浦发银行|浦发银行|金融|https://www.spdb.com.cn/campus|https://www.spdb.com.cn/campus|浦发招聘|spdb',
    '民生银行|民生银行|金融|https://www.cmbc.com.cn/campus|https://www.cmbc.com.cn/campus|民生招聘|cmbc',
    '光大银行|光大银行|金融|https://www.cebbank.com/campus|https://www.cebbank.com/campus|光大招聘|cebbank',
    -- ═══ 电商 / 零售 ═══
    '得物|得物|电商|https://campus.dewu.com/|https://campus.dewu.com/|得物招聘|dewu|poizon',
    '唯品会|唯品会|电商|https://campus.vip.com/|https://campus.vip.com/|唯品会招聘|vip|vip.com',
    '云集|云集|电商|https://www.yunjicollection.com/campus|https://www.yunjicollection.com/campus|云集招聘',
    '每日优鲜|每日优鲜|电商|https://campus.missfresh.cn/|https://campus.missfresh.cn/|每日优鲜招聘',
    '叮咚买菜|叮咚|电商|https://campus.dingdongama.com/|https://campus.dingdongama.com/|叮咚招聘',
    '兴盛优选|兴盛|电商|https://campus.xingsheng.com/|https://campus.xingsheng.com/|兴盛招聘',
    '本来生活|本来|生鲜|https://www.benlai.com/campus|https://www.benlai.com/campus|本来招聘',
    '多点Dmall|多点|零售|https://www.dmall.com/campus|https://www.dmall.com/campus|多点招聘|dmall',
    '物美|物美|零售|https://www.wumart.com/campus|https://www.wumart.com/campus|物美招聘|wumart',
    '便利蜂|便利蜂|零售|https://campus.bl.com/|https://campus.bl.com/|便利蜂招聘|bl',
    '名创优品|名创|零售|https://www.miniso.com/campus|https://www.miniso.com/campus|名创招聘|miniso',
    '泡泡玛特|泡泡玛特|零售|https://www.popmart.com/campus|https://www.popmart.com/campus|泡泡玛特招聘|popmart',
    '完美日记|完美日记|美妆|https://www.perfectcorp.com/campus|https://www.perfectcorp.com/campus|完美日记招聘|perfume',
    '花西子|花西子|美妆|https://www.huaxizi.com/campus|https://www.huaxizi.com/campus|花西子招聘',
    '薇诺娜|薇诺娜|美妆|https://www.winnermicro.com/campus|https://www.winnermicro.com/campus|薇诺娜招聘',
    '元气森林|元气森林|饮料|https://www.yuanqishenglin.com/campus|https://www.yuanqishenglin.com/campus|元气招聘',
    '三只松鼠|三只松鼠|零食|https://campus.3songshu.com/|https://campus.3songshu.com/|松鼠招聘|3songshu',
    '良品铺子|良品铺子|零食|https://www.lppz.com/campus|https://www.lppz.com/campus|良品招聘|lppz',
    '百草味|百草味|零食|https://www.bcb.com/campus|https://www.bcb.com/campus|百草味招聘',
    -- ═══ 物流 / 供应链 ═══
    '菜鸟网络|菜鸟|物流|https://campus.cainiao.com/|https://campus.cainiao.com/|菜鸟招聘',
    '顺丰速运|顺丰|物流|https://campus.sf-express.com/|https://campus.sf-express.com/|顺丰招聘|sf|sf-express',
    '京东物流|京东|物流|https://careers.jd.com/|https://careers.jd.com/|京东物流招聘',
    '中通快递|中通|物流|https://www.zto.com/campus|https://www.zto.com/campus|中通招聘|zto',
    '圆通速递|圆通|物流|https://www.yto.net.cn/campus|https://www.yto.net.cn/campus|圆通招聘|yto',
    '韵达快递|韵达|物流|https://www.yundaex.com/campus|https://www.yundaex.com/campus|韵达招聘|yunda',
    '申通快递|申通|物流|https://www.sto.cn/campus|https://www.sto.cn/campus|申通招聘|sto',
    '百世快递|百世|物流|https://www.800best.com/campus|https://www.800best.com/campus|百世招聘|best',
    '满帮集团|满帮|物流|https://campus.mangobtl.com/|https://campus.mangobtl.com/|满帮招聘|mangobtl',
    '福佑卡车|福佑|物流|https://www.fuyoukache.com/campus|https://www.fuyoukache.com/campus|福佑招聘',
    '货拉拉|货拉拉|物流|https://www.huolala.cn/campus|https://www.huolala.cn/campus|货拉拉招聘|huolala',
    'G7|G7|物流|https://www.g7.com.cn/campus|https://www.g7.com.cn/campus|G7招聘',
    '路歌|路歌|物流|https://www.logchina.com/campus|https://www.logchina.com/campus|路歌招聘',
    '准时达|准时达|供应链|https://www.ctc.com/campus|https://www.ctc.com/campus|准时达招聘|ctc',
    '日日顺|日日顺|供应链|https://www.rrs.com/campus|https://www.rrs.com/campus|日日顺招聘|rrs',
    '安能物流|安能|物流|https://www.ane56.com/campus|https://www.ane56.com/campus|安能招聘|ane56',
    -- ═══ 教育科技 ═══
    '一起教育|一起学|教育|https://campus.17zuoye.com/|https://campus.17zuoye.com/|一起招聘',
    '火花思维|火花|教育|https://campus.huohua.cn/|https://campus.huohua.cn/|火花招聘',
    '豌豆思维|豌豆|教育|https://campus.peaidea.com/|https://campus.peaidea.com/|豌豆招聘',
    '松鼠AI|松鼠AI|教育|https://campus.songshu.ai/|https://campus.songshu.ai/|松鼠招聘',
    '一起学网校|一起学|教育|https://campus.17zuoye.com/|https://campus.17zuoye.com/|一起学招聘',
    '网易云课堂|网易|教育|https://campus.study.163.com/|https://campus.study.163.com/|云课堂招聘',
    '腾讯课堂|腾讯|教育|https://ke.qq.com/campus|https://ke.qq.com/campus|腾讯课堂招聘',
    '沪江|沪江|教育|https://www.hujiang.com/campus|https://www.hujiang.com/campus|沪江招聘|hujiang',
    -- ═══ 招聘平台 / 人力资源 ═══
    '牛客|牛客|招聘平台|https://www.nowcoder.com/enterprise|https://www.nowcoder.com/enterprise|牛客招聘平台',
    '实习僧|实习僧|招聘平台|https://www.shixiseng.com/campus|https://www.shixiseng.com/campus|实习僧招聘',
    'BOSS直聘|BOSS|招聘平台|https://www.zhipin.com/|https://www.zhipin.com/|BOSS直聘',
    '拉勾网|拉勾|招聘平台|https://www.lagou.com/|https://www.lagou.com/|拉勾招聘|lagou',
    '智联招聘|智联|招聘平台|https://xiaozuan.zhaopin.com/campus|https://xiaozuan.zhaopin.com/campus|智联校招',
    '前程无忧|51job|招聘平台|https://www.51job.com/campus|https://www.51job.com/campus|51job校招',
    '猎聘|猎聘|招聘平台|https://www.liepin.com/campus|https://www.liepin.com/campus|猎聘校招|liepin',
    '脉脉|脉脉|职场社交|https://campus.maimai.cn/|https://campus.maimai.cn/|脉脉招聘|maimai',
    -- ═══ 内容 / 社交 ═══
    '探探|探探|社交|https://campus.tantanapp.com/|https://campus.tantanapp.com/|探探招聘|tantan',
    '积木|积木|社交|https://www.jimuu.com/campus|https://www.jimuu.com/campus|积木招聘|jimuu',
    '最右|最右|社交|https://campus.zuiyou.com/|https://campus.zuiyou.com/|最右招聘|zuiyou',
    'ONE一个|ONE|内容|https://campus.wufazhuce.com/|https://campus.wufazhuce.com/|ONE招聘',
    '即刻|即刻|社区|https://campus.jike.com/|https://campus.jike.com/|即刻招聘|jike',
    '知乎|知乎|问答|https://campus.zhihu.com/|https://campus.zhihu.com/|知乎招聘|zhihu',
    '豆瓣|豆瓣|社区|https://www.douban.com/campus|https://www.douban.com/campus|豆瓣招聘|douban',
    -- ═══ 运营商 / 通信 ═══
    '中国移动|移动|运营商|https://career.10086.cn/campus|https://career.10086.cn/campus|移动招聘|cmcc',
    '中国电信|电信|运营商|https://www.chinatelecom.com.cn/campus|https://www.chinatelecom.com.cn/campus|电信招聘|ctc',
    '中国联通|联通|运营商|https://career.chinaunicom.cn/campus|https://career.chinaunicom.cn/campus|联通招聘|cucc',
    '中国铁塔|铁塔|通信|https://www.tower.com.cn/campus|https://www.tower.com.cn/campus|铁塔招聘|tower',
    '中兴通讯|中兴|通信|https://job.zte.com.cn/campus|https://job.zte.com.cn/campus|中兴招聘|zte',
    '烽火通信|烽火|通信|https://www.fiberhome.com/campus|https://www.fiberhome.com/campus|烽火招聘|fiberhome',
    '上海诺基亚贝尔|诺基亚|通信|https://www.nokia-sbell.com/campus|https://www.nokia-sbell.com/campus|诺基亚招聘',
    '爱立信|爱立信|通信|https://www.ericsson.com/careers|https://www.ericsson.com/careers|爱立信招聘|ericsson',
    '思科|Cisco|通信|https://www.cisco.com/cn/careers|https://www.cisco.com/cn/careers|思科招聘|cisco',
    '诺基亚|诺基亚|通信|https://www.nokia.com/careers|https://www.nokia.com/careers|',
    '紫光集团|紫光|通信|https://www.unigroup.com.cn/campus|https://www.unigroup.com.cn/campus|紫光招聘|unigroup',
    '展讯通信|展讯|芯片|https://www.spreadtrum.com/campus|https://www.spreadtrum.com/campus|展讯招聘|spreadtrum',
    '锐迪科|RDA|芯片|https://www.rdamicro.com/campus|https://www.rdamicro.com/campus|RDA招聘',
    '中芯国际|SMIC|芯片|https://www.smics.com/campus|https://www.smics.com/campus|中芯招聘|smic',
    '华虹半导体|华虹|芯片|https://www.hua.hong.com/campus|https://www.hua.hong.com/campus|华虹招聘|huali',
    '长江存储|长江存储|存储|https://www.ymtc.com/campus|https://www.ymtc.com/campus|长江存储招聘|ymtc|ymt',
    '长鑫存储|长鑫|存储|https://www.cxmt.com/campus|https://www.cxmt.com/campus|长鑫招聘|cxmt',
    -- ═══ 外企中国分部 ═══
    '微软|微软|软件|https://careers.microsoft.com/|https://careers.microsoft.com/|微软招聘|microsoft|ms',
    '谷歌|谷歌|互联网|https://careers.google.com/|https://careers.google.com/|谷歌招聘|google|goog',
    'Meta|Meta|互联网|https://www.metacareers.com/|https://www.metacareers.com/|Meta招聘|meta|facebook',
    'Apple|苹果|硬件|https://www.apple.com/cn/careers|https://www.apple.com/cn/careers|苹果招聘|apple',
    'Amazon|亚马逊|电商|https://www.amazon.jobs/en/locations/china|https://www.amazon.jobs/en/locations/china|亚马逊招聘|amazon|amz',
    'Netflix|Netflix|流媒体|https://jobs.netflix.com/|https://jobs.netflix.com/|Netflix招聘',
    'Salesforce|Salesforce|SaaS|https://www.salesforce.com/careers|https://www.salesforce.com/careers|Salesforce招聘',
    'SAP|SAP|ERP|https://jobs.sap.com/cn|https://jobs.sap.com/cn|SAP招聘',
    'Oracle|Oracle|数据库|https://www.oracle.com/careers|https://www.oracle.com/careers|Oracle招聘',
    'IBM|IBM|IT服务|https://www.ibm.com/cn/careers|https://www.ibm.com/cn/careers|IBM招聘',
    'Cisco|Cisco|网络|https://www.cisco.com/cn/careers|https://www.cisco.com/cn/careers|Cisco招聘',
    'Intel|Intel|芯片|https://jobs.intel.com/cn|https://jobs.intel.com/cn|Intel招聘',
    'NVIDIA|NVIDIA|芯片|https://www.nvidia.com/en-us/careers|https://www.nvidia.com/en-us/careers|NVIDIA招聘',
    'Qualcomm|Qualcomm|芯片|https://www.qualcomm.com/careers|https://www.qualcomm.com/careers|Qualcomm招聘',
    'TSMC|台积电|芯片|https://www.tsmc.com/careers|https://www.tsmc.com/careers|台积电招聘|tsmc',
    'Samsung|三星|硬件|https://www.samsung.com/cn/careers|https://www.samsung.com/cn/careers|三星招聘|samsung',
    'Micron|美光|存储|https://www.micron.com/careers|https://www.micron.com/careers|美光招聘|micron',
    'SK海力士|SK海力士|存储|https://www.sk.com/careers|https://www.sk.com/careers|SK招聘|skhynix',
    'eBay|eBay|电商|https://careers.ebay.com.cn/|https://careers.ebay.com.cn/|eBay招聘',
    'PayPal|PayPal|支付|https://www.paypal.com/cn/careers|https://www.paypal.com/cn/careers|PayPal招聘',
    'Airbnb|Airbnb|旅游|https://careers.airbnb.com/|https://careers.airbnb.com/|Airbnb招聘',
    'Uber|Uber|出行|https://www.uber.com/cn/careers|https://www.uber.com/cn/careers|Uber招聘',
    'Lyft|Lyft|出行|https://www.lyft.com/careers|https://www.lyft.com/careers|Lyft招聘',
    'Stripe|Stripe|支付|https://stripe.com/cn/careers|https://stripe.com/cn/careers|Stripe招聘',
    'Coinbase|Coinbase|区块链|https://www.coinbase.com/careers|https://www.coinbase.com/careers|Coinbase招聘',
    'Shopify|Shopify|电商|https://www.shopify.com/careers|https://www.shopify.com/careers|Shopify招聘',
    'Zoom|Zoom|视频|https://zoom.us/careers|https://zoom.us/careers|Zoom招聘',
    'Atlassian|Atlassian|工具|https://www.atlassian.com/careers|https://www.atlassian.com/careers|Atlassian招聘',
    'Databricks|Databricks|数据|https://www.databricks.com/careers|https://www.databricks.com/careers|Databricks招聘',
    'Snowflake|Snowflake|数据|https://www.snowflake.com/careers|https://www.snowflake.com/careers|Snowflake招聘',
    'MongoDB|MongoDB|数据库|https://www.mongodb.com/careers|https://www.mongodb.com/careers|MongoDB招聘',
    'Elastic|Elastic|搜索|https://www.elastic.co/careers|https://www.elastic.co/careers|Elastic招聘',
    'Cloudflare|Cloudflare|CDN|https://www.cloudflare.com/careers|https://www.cloudflare.com/careers|Cloudflare招聘',
    'Datadog|Datadog|监控|https://www.datadog.com/careers|https://www.datadog.com/careers|Datadog招聘',
    'GitLab|GitLab|工具|https://about.gitlab.com/jobs/|https://about.gitlab.com/jobs/|GitLab招聘',
    'HashiCorp|HashiCorp|工具|https://www.hashicorp.com/careers|https://www.hashicorp.com/careers|HashiCorp招聘',
    -- ═══ 其他知名科技公司 ═══
    '同花顺|同花顺|金融|https://www.10jqka.com.cn/campus|https://www.10jqka.com.cn/campus|同花顺招聘|10jqka',
    '东方财富|东方财富|金融|https://www.eastmoney.com/campus|https://www.eastmoney.com/campus|东财招聘|eastmoney',
    '恒生电子|恒生|金融|https://www.hundsun.com/campus|https://www.hundsun.com/campus|恒生招聘|hundsun',
    '金证股份|金证|金融|https://www.szkingdom.com/campus|https://www.szkingdom.com/campus|金证招聘|kingdom',
    '新晨科技|新晨|金融|https://www.suncreate.com/campus|https://www.suncreate.com/campus|新晨招聘',
    '宇信科技|宇信|金融|https://www.yuxin.com/campus|https://www.yuxin.com/campus|宇信招聘|yuxin',
    '长亮科技|长亮|金融|https://www.sunline.cn/campus|https://www.sunline.cn/campus|长亮招聘|sunline',
    '科蓝软件|科蓝|金融|https://www.careerstart.com/campus|https://www.careerstart.com/campus|科蓝招聘',
    '高伟达|高伟达|金融|https://www.gaoweida.com/campus|https://www.gaoweida.com/campus|高伟达招聘',
    '新国都|新国都|支付|https://www.xgd.com/campus|https://www.xgd.com/campus|新国都招聘',
    '拉卡拉|拉卡拉|支付|https://www.lakala.com/campus|https://www.lakala.com/campus|拉卡拉招聘|lakala',
    '移卡|移卡|支付|https://www.yikafu.com/campus|https://www.yikafu.com/campus|移卡招聘|yikafu',
    '移远通信|移远|通信|https://www.quectel.com/campus|https://www.quectel.com/campus|移远招聘|quectel',
    '广和通|广和通|通信|https://www.fibocom.com/campus|https://www.fibocom.com/campus|广和通招聘|fibocom',
    '日海智能|日海|IoT|https://www.sunlike.com.cn/campus|https://www.sunlike.com.cn/campus|日海招聘',
    '有方科技|有方|IoT|https://www.neoway.com.cn/campus|https://www.neoway.com.cn/campus|有方招聘|neoway',
    '利尔达|利尔达|IoT|https://www.lierda.com/campus|https://www.lierda.com/campus|利尔达招聘|lierda',
    '映翰通|映翰通|IoT|https://www.easigreen.com/campus|https://www.easigreen.com/campus|映翰通招聘',
    '三旺通信|三旺|IoT|https://www.3onedata.com/campus|https://www.3onedata.com/campus|三旺招聘|3onedata',
    '华测导航|华测|北斗|https://www.huace.cn/campus|https://www.huace.cn/campus|华测招聘|huace',
    '合众思壮|合众|北斗|https://www.unistrong.com/campus|https://www.unistrong.com/campus|合众招聘',
    '药明康德|药明|医药|https://www.wuxiapptec.com/campus|https://www.wuxiapptec.com/campus|药明招聘|wuxi',
    '药明生物|药明|医药|https://www.wuxibiologics.com/campus|https://www.wuxibiologics.com/campus|',
    '泰格医药|泰格|医药|https://www.tigermedgrp.com/campus|https://www.tigermedgrp.com/campus|泰格招聘|tigermed',
    '康龙化成|康龙|医药|https://www.pharmaron.com/campus|https://www.pharmaron.com/campus|康龙招聘|pharmaron',
    '金斯瑞|金斯瑞|生物|https://www.genscript.com.cn/campus|https://www.genscript.com.cn/campus|金斯瑞招聘|genscript',
    '晶泰科技|晶泰|AI制药|https://www.xtalpi.com/campus|https://www.xtalpi.com/campus|晶泰招聘|xtalpi',
    '英矽智能|英矽|AI制药|https://www.insilico.com/campus|https://www.insilico.com/campus|英矽招聘|insilico',
  ];

  row_data TEXT;
  parts TEXT[];
  v_company_id BIGINT;
  v_careers_id BIGINT;
  insert_count INT := 0;
  company_count INT := 0;
  skip_count INT := 0;
  alias_arr TEXT[];
  i INT;
BEGIN
  -- 删除旧的种子数据
  DELETE FROM company_careers WHERE source = 'real_seed';

  FOREACH row_data IN ARRAY company_data LOOP
    parts := string_to_array(row_data, '|');
    IF array_length(parts, 1) < 5 THEN
      skip_count := skip_count + 1;
      CONTINUE;
    END IF;

    -- parts[1]=name, [2]=alias, [3]=industry, [4]=careers_url, [5]=detail_url
    alias_arr := string_to_array(parts[2], ',');

    -- 插入或更新公司
    INSERT INTO companies (name, alias_names, industry, fame_score)
    VALUES (parts[1], alias_arr, parts[3], 50)
    ON CONFLICT (name) DO NOTHING
    RETURNING id INTO v_company_id;

    IF v_company_id IS NULL THEN
      SELECT id INTO v_company_id FROM companies WHERE name = parts[1] LIMIT 1;
    END IF;

    IF v_company_id IS NOT NULL THEN
      INSERT INTO company_careers (company_id, careers_url, detail_url, source, status)
      VALUES (v_company_id, parts[4], parts[5], 'real_seed', 'pending')
      ON CONFLICT (company_id, careers_url) DO NOTHING
      RETURNING id INTO v_careers_id;

      IF v_careers_id IS NOT NULL THEN
        insert_count := insert_count + 1;
      END IF;
      company_count := company_count + 1;
    ELSE
      skip_count := skip_count + 1;
    END IF;

    -- 每100条打印进度
    IF company_count % 100 = 0 THEN
      RAISE NOTICE 'Progress: % companies processed', company_count;
    END IF;
  END LOOP;

  RAISE NOTICE 'Company careers seed complete: % companies inserted, % total processed, % skipped',
    insert_count, company_count, skip_count;
END $$;
